// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/about/index.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/users.ts";
import * as $4 from "./routes/api/users/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/users/[name].tsx";
import * as $7 from "./routes/users/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/UserData.tsx";
import * as $$2 from "./islands/Users.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/about/index.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/users.ts": $3,
    "./routes/api/users/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/users/[name].tsx": $6,
    "./routes/users/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/UserData.tsx": $$1,
    "./islands/Users.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
